# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: devel
sudo: FALSE
compiler: clang

cache:
  apt: true
  packages: true
  ccache: true

addons:
  apt:
    packages:
      - libudunits2-dev
      - libv8-dev
      - libgsl-dev
      - libgdal-dev
      - libproj-dev
